version: "2.4"
services:

  mysql:
    image: mysql:8.0.31
    container_name: mysql
    environment:
      - MYSQL_DATABASE=qualidade-ar
      - MYSQL_ROOT_PASSWORD=s3cr3t
      - MYSQL_USER=qauser
      - MYSQL_PASSWORD=qapass
    volumes:
      - ./qualidade-ar.sql:/docker-entrypoint-initdb.d/qualidade-ar.sql
      - mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
    healthcheck:
      test: mysql -u qauser -pqapass -e 'use qualidade-ar;select count(*) from qualidadeAr;'
      interval: 10s
      timeout: 5s
      retries: 20

  mysql_admin:
    image: phpmyadmin:5.2.0-apache
    container_name: mysql_admin
    environment:
      - PMA_HOST=mysql
    volumes:
      - mysql_admin_data:/sessions
    ports:
      - 8090:80
    depends_on:
      mysql:
        condition: service_healthy

  api:
    image: esignbr/qualidade-ar-brasil
    container_name: api
    environment:
      - MYSQL_HOST=mysql
    ports:
      - 8080:8080
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data:
  mysql_admin_data:
